import "./../globals.css";
export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className=" container">
        <div
          className=" flex items-center justify-center border-2 container  dark:bg-[#121415] overflow-hidden relative md:rounded-[30px]  mx-auto  bg-white md:mt-14 mb-52  h-auto
                      shadow-[0_8px_30px_rgb(0,0,0,0.08)]"
        >
          {children}
        </div>
      </body>
    </html>
  );
}
