import { i18n } from "@/i18n-config";
import Image from "next/image";
import "@/app/[lang]/globals.css";
import ellipse from "@/svg/ellipse.svg";
import localFont from "next/font/local";
import Providers from "@/app/[lang]/provider";
import Navbar from "@/app/[lang]/components/navbar/Navbar";
import { getDictionary } from "@/get-dictionary";
import { cn } from "@/lib/utils";

const iransans = localFont({
  src: [
    // {
    //   path: "../../public/fonts/IRANSansWeb.eot",
    //   weight: "400",
    // },
    {
      path: "../../../../public/fonts/IRANSansWeb.ttf",
      weight: "400",
    },
    {
      path: "../../../../public/fonts/IRANSansWeb.woff",
      weight: "700",
    },
    {
      path: "../../../../public/fonts/IRANSansWeb.woff2",
      weight: "700",
    },
  ],
  variable: "--font-iransans",
});
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export async function generateStaticParams() {
  return i18n.locales.map((locale) => ({ lang: locale }));
}

export default async function Root({
  children,
  params,
  authModal,
}: {
  children: React.ReactNode;
  params: { lang: string };
  authModal: React.ReactNode;
}) {
  // console.log(params.lang);

  const dictionary = await getDictionary(params.lang);

  return (
    <html
      lang={params.lang}
      dir={params.lang === "ar" ? "rtl" : "ltr"}
      className={cn("antialiased", iransans.className)}
    >
      {/* /${barlowCondensed.className} ${inter.className} ${merriweather.variable} ${roboto.className} ${iransans.className} font-sans/ */}
      {/* className={`${iransans.className}`}  */}
      <body className="antialiased bg-gradient-to-r from-[#f1ece0] to-[#D6DDE2]">
        <div
          className=" container  dark:bg-slate-900 overflow-hidden relative md:rounded-[30px]  mx-auto  bg-white md:mt-14 mb-52  h-full
                      shadow-[0_8px_30px_rgb(0,0,0,0.08)]"
        >
          <Providers>
            {/* <Navbar
              navmenu={dictionary.navbar}
              siteLogo={dictionary.logo}
            ></Navbar> */}
            <div className="flex flex-row h-screen">
              <div className=" w-[80px] rounded-[15px] bg-[#eef2f5] m-4"></div>
              <div className="flex-grow m-4 border"></div>
            </div>
            {children}
          </Providers>
        </div>
      </body>
    </html>
  );
}
